= Chef and Queries
aryang_adm
:author: aryanag_adm
:tester: iscsi
:editorial: https://discuss.codechef.com/problems/CHEFQUER
:stem:

Problem from codechef: https://www.codechef.com/START5C/problems/CHEFQUER

You are given a sequence stem:[A_1, A_2, ..., A_N].
Chef wants you to handle stem:[Q] queries.
There are two types of queries:

- `1 L R X`: for each stem:[i, (L \leq i \leq R)], add stem:[(X + i - L)^2] to stem:[A_i]
- `2 Y`: find the current value of stem:[A_Y]

== Input

- The first line of the input contains two space-separated integers stem:[N] and stem:[Q].
- The second line contains stem:[N] space-separated integers stem:[A_1, A_2, ..., A_N].
- stem:[Q] lines follow. Each of these lines describes a query in the format described above.

== Output

For each query of the second type, print a single line containing one integer stem:[A_Y].

== Constraints

- stem:[1 \leq N, Q \leq 10^5]
- stem:[0 \leq |A_i| \leq 10^6] for each valid stem:[i]
- stem:[1 \leq L \leq R \leq N]
- stem:[0 \leq |X| \leq 10^6]
- stem:[1 \leq Y \leq N]

== Example Input

[source]
----
5 4
1 10 3 6 5
1 1 3 5
2 3
1 4 5 7
2 5
----

== Example Output

[source]
----
52
69
----

== Explanation

- the sequence after the first query is
+
stem:[\[1 + 5^2, 10 + (5 + 2 - 1)^2, 3 + (5 + 3 - 1)^2, 6, 5\] = \[26, 46, 52, 6, 5\]]

- the second query asks for stem:[A_3], which is stem:[52]

- the sequence after the third query is
+
stem:[\[26, 46, 52, 6 + 7^2, 5 + (7 + 1)^2\] = \[26, 46, 52, 55, 69\]]

- the second query asks for stem:[A_5], which is stem:[69]
